/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design.versionz;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author vuongluis
 */
public class demo extends javax.swing.JFrame {

    /**
     * Creates new form demo
     */
    public demo() {
        initComponents();
        ImageIcon image = new ImageIcon(getClass().getResource("/images/cho.gif"));
        this.setIconImage(image.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Navigation = new javax.swing.JPanel();
        PanelMarginResize = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        MainContent = new javax.swing.JPanel();
        Content = new javax.swing.JPanel();
        BorderPanelLeft = new javax.swing.JPanel();
        BorderPanelLoaiHang = new javax.swing.JPanel();
        PanelLoaiHang = new javax.swing.JPanel();
        BorderPanelTimKiem = new javax.swing.JPanel();
        PanelTiemKiem = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        BorderPanelLuaChon = new javax.swing.JPanel();
        PanelLuachon = new javax.swing.JPanel();
        BorderPanelRight = new javax.swing.JPanel();
        ContentPanelRight = new javax.swing.JPanel();
        Footer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(880, 548));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(880, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-vinaenter.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Hotline: 0905.051.720 - 0989.623.886");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 430, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(10, 10, 10))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(40, 40, 40))
        );

        getContentPane().add(Header, java.awt.BorderLayout.NORTH);

        Navigation.setBackground(new java.awt.Color(255, 255, 255));
        Navigation.setPreferredSize(new java.awt.Dimension(880, 40));
        Navigation.setLayout(new java.awt.BorderLayout());

        PanelMarginResize.setBackground(new java.awt.Color(255, 102, 102));
        PanelMarginResize.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 10, new java.awt.Color(255, 255, 255)));
        PanelMarginResize.setForeground(new java.awt.Color(255, 255, 255));
        PanelMarginResize.setPreferredSize(new java.awt.Dimension(880, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/001_20.png"))); // NOI18N
        jButton1.setText("Tổng quát");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/001_46.png"))); // NOI18N
        jButton2.setText("Hàng hóa");
        jButton2.setContentAreaFilled(false);
        jButton2.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/001_57.png"))); // NOI18N
        jButton3.setText("Phòng ban");
        jButton3.setContentAreaFilled(false);
        jButton3.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/001_47.png"))); // NOI18N
        jButton4.setText("Giao dịch");
        jButton4.setContentAreaFilled(false);
        jButton4.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/001_18.png"))); // NOI18N
        jButton5.setText("Đối tác");
        jButton5.setContentAreaFilled(false);
        jButton5.setMargin(new java.awt.Insets(2, 2, 2, 2));

        javax.swing.GroupLayout PanelMarginResizeLayout = new javax.swing.GroupLayout(PanelMarginResize);
        PanelMarginResize.setLayout(PanelMarginResizeLayout);
        PanelMarginResizeLayout.setHorizontalGroup(
            PanelMarginResizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMarginResizeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap(360, Short.MAX_VALUE))
        );
        PanelMarginResizeLayout.setVerticalGroup(
            PanelMarginResizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMarginResizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelMarginResizeLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jButton5)))
        );

        Navigation.add(PanelMarginResize, java.awt.BorderLayout.CENTER);

        getContentPane().add(Navigation, java.awt.BorderLayout.CENTER);

        MainContent.setBackground(new java.awt.Color(255, 255, 255));
        MainContent.setPreferredSize(new java.awt.Dimension(880, 470));
        MainContent.setLayout(new java.awt.BorderLayout());

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setPreferredSize(new java.awt.Dimension(880, 433));
        Content.setLayout(new java.awt.BorderLayout());

        BorderPanelLeft.setBackground(new java.awt.Color(255, 255, 255));
        BorderPanelLeft.setLayout(new java.awt.BorderLayout());

        BorderPanelLoaiHang.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 0, new java.awt.Color(255, 255, 255)));

        PanelLoaiHang.setBackground(new java.awt.Color(255, 255, 255));
        PanelLoaiHang.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 102)), "Loại hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 102, 102))); // NOI18N

        javax.swing.GroupLayout PanelLoaiHangLayout = new javax.swing.GroupLayout(PanelLoaiHang);
        PanelLoaiHang.setLayout(PanelLoaiHangLayout);
        PanelLoaiHangLayout.setHorizontalGroup(
            PanelLoaiHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        PanelLoaiHangLayout.setVerticalGroup(
            PanelLoaiHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BorderPanelLoaiHangLayout = new javax.swing.GroupLayout(BorderPanelLoaiHang);
        BorderPanelLoaiHang.setLayout(BorderPanelLoaiHangLayout);
        BorderPanelLoaiHangLayout.setHorizontalGroup(
            BorderPanelLoaiHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLoaiHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BorderPanelLoaiHangLayout.setVerticalGroup(
            BorderPanelLoaiHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLoaiHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BorderPanelLeft.add(BorderPanelLoaiHang, java.awt.BorderLayout.CENTER);

        BorderPanelTimKiem.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 0, new java.awt.Color(255, 255, 255)));
        BorderPanelTimKiem.setPreferredSize(new java.awt.Dimension(0, 80));
        BorderPanelTimKiem.setLayout(new java.awt.BorderLayout());

        PanelTiemKiem.setBackground(new java.awt.Color(255, 255, 255));
        PanelTiemKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 102)), "Tìm kiếm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 102, 102))); // NOI18N

        tfSearch.setToolTipText("");
        tfSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout PanelTiemKiemLayout = new javax.swing.GroupLayout(PanelTiemKiem);
        PanelTiemKiem.setLayout(PanelTiemKiemLayout);
        PanelTiemKiemLayout.setHorizontalGroup(
            PanelTiemKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTiemKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTiemKiemLayout.setVerticalGroup(
            PanelTiemKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTiemKiemLayout.createSequentialGroup()
                .addComponent(tfSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        BorderPanelTimKiem.add(PanelTiemKiem, java.awt.BorderLayout.CENTER);

        BorderPanelLeft.add(BorderPanelTimKiem, java.awt.BorderLayout.PAGE_START);

        BorderPanelLuaChon.setBackground(new java.awt.Color(102, 255, 255));
        BorderPanelLuaChon.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 0, new java.awt.Color(255, 255, 255)));
        BorderPanelLuaChon.setForeground(new java.awt.Color(255, 255, 255));
        BorderPanelLuaChon.setLayout(new java.awt.BorderLayout());

        PanelLuachon.setBackground(new java.awt.Color(255, 255, 255));
        PanelLuachon.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 102)), "Lựa chọn hiển thị", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 102, 102))); // NOI18N

        javax.swing.GroupLayout PanelLuachonLayout = new javax.swing.GroupLayout(PanelLuachon);
        PanelLuachon.setLayout(PanelLuachonLayout);
        PanelLuachonLayout.setHorizontalGroup(
            PanelLuachonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        PanelLuachonLayout.setVerticalGroup(
            PanelLuachonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        BorderPanelLuaChon.add(PanelLuachon, java.awt.BorderLayout.CENTER);

        BorderPanelLeft.add(BorderPanelLuaChon, java.awt.BorderLayout.PAGE_END);

        Content.add(BorderPanelLeft, java.awt.BorderLayout.CENTER);

        BorderPanelRight.setBackground(new java.awt.Color(255, 102, 153));
        BorderPanelRight.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(255, 255, 255)));
        BorderPanelRight.setPreferredSize(new java.awt.Dimension(560, 406));
        BorderPanelRight.setLayout(new java.awt.BorderLayout());

        ContentPanelRight.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(255, 102, 102)));
        ContentPanelRight.setPreferredSize(new java.awt.Dimension(506, 404));

        javax.swing.GroupLayout ContentPanelRightLayout = new javax.swing.GroupLayout(ContentPanelRight);
        ContentPanelRight.setLayout(ContentPanelRightLayout);
        ContentPanelRightLayout.setHorizontalGroup(
            ContentPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        ContentPanelRightLayout.setVerticalGroup(
            ContentPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        BorderPanelRight.add(ContentPanelRight, java.awt.BorderLayout.CENTER);

        Content.add(BorderPanelRight, java.awt.BorderLayout.EAST);

        MainContent.add(Content, java.awt.BorderLayout.PAGE_START);

        Footer.setBackground(new java.awt.Color(214, 217, 223));
        Footer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 10, 10, 10, new java.awt.Color(255, 255, 255)));
        Footer.setPreferredSize(new java.awt.Dimension(880, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Copyright by © VinaENTER EDU. Coby by ABC");

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        MainContent.add(Footer, java.awt.BorderLayout.CENTER);

        getContentPane().add(MainContent, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BorderPanelLeft;
    private javax.swing.JPanel BorderPanelLoaiHang;
    private javax.swing.JPanel BorderPanelLuaChon;
    private javax.swing.JPanel BorderPanelRight;
    private javax.swing.JPanel BorderPanelTimKiem;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel ContentPanelRight;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel MainContent;
    private javax.swing.JPanel Navigation;
    private javax.swing.JPanel PanelLoaiHang;
    private javax.swing.JPanel PanelLuachon;
    private javax.swing.JPanel PanelMarginResize;
    private javax.swing.JPanel PanelTiemKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
