/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author vuongluis
 */
public class demo extends javax.swing.JFrame {

    /**
     * Creates new form demo
     */
    public demo() {
        ImageIcon image = new ImageIcon(getClass().getResource("/images/title.png"));
        this.setIconImage(image.getImage());
        this.setResizable(false);
        this.setTitle("Game Cân Não");
        this.setFont(new Font("Arial",13,Font.BOLD));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        line = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        linex = new javax.swing.JLabel();
        liney = new javax.swing.JLabel();
        btnCode = new javax.swing.JButton();
        code = new javax.swing.JLabel();
        btnEnglish = new javax.swing.JButton();
        english = new javax.swing.JLabel();
        btnJapan = new javax.swing.JButton();
        japanese = new javax.swing.JLabel();
        ThuTuCauHoi = new javax.swing.JLabel();
        DauHoi = new javax.swing.JLabel();
        linexa = new javax.swing.JLabel();
        linexb = new javax.swing.JLabel();
        linexc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        areax = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("BRAIN GAME BALANCE");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 280, 40));

        line.setForeground(new java.awt.Color(255, 255, 255));
        line.setText("___________________________________________________________________________");
        getContentPane().add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 460, -1));

        description.setFont(new java.awt.Font("Bell MT", 2, 24)); // NOI18N
        description.setForeground(new java.awt.Color(255, 255, 255));
        description.setText("Imagination is more important than knowledge");
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 440, 30));

        linex.setForeground(new java.awt.Color(255, 255, 255));
        linex.setText("_______________________");
        getContentPane().add(linex, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 160, -1));

        liney.setForeground(new java.awt.Color(255, 255, 255));
        liney.setText("_______________________");
        getContentPane().add(liney, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        btnCode.setContentAreaFilled(false);
        btnCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 213, 140, 40));

        code.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/programming.png"))); // NOI18N
        getContentPane().add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        btnEnglish.setContentAreaFilled(false);
        btnEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnglishActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 303, 140, 40));

        english.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/english.png"))); // NOI18N
        getContentPane().add(english, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        btnJapan.setContentAreaFilled(false);
        btnJapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJapanActionPerformed(evt);
            }
        });
        getContentPane().add(btnJapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 140, 30));

        japanese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/japanese.png"))); // NOI18N
        getContentPane().add(japanese, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        ThuTuCauHoi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ThuTuCauHoi.setForeground(new java.awt.Color(150, 61, 61));
        ThuTuCauHoi.setText("Question 1:");
        getContentPane().add(ThuTuCauHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        DauHoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question.png"))); // NOI18N
        getContentPane().add(DauHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        linexa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        linexa.setForeground(new java.awt.Color(150, 61, 61));
        linexa.setText("----------------------------------------------------------------------------");
        getContentPane().add(linexa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        linexb.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        linexb.setForeground(new java.awt.Color(150, 61, 61));
        linexb.setText("--------------------------------------------------------");
        getContentPane().add(linexb, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        linexc.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        linexc.setForeground(new java.awt.Color(150, 61, 61));
        linexc.setText("----------------------------------------------------------------------------");
        getContentPane().add(linexc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/answer.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(150, 61, 61));
        jLabel2.setText("Please choose the most correct answer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Đáp án D");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 460, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Đáp án A");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 460, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Đáp án B");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 460, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Đáp án C");
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 460, -1));

        areax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/areax.png"))); // NOI18N
        getContentPane().add(areax, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\vuongluis\\Desktop\\material\\background.png")); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Chào mừng bạn đến với trắc nghiệm lập trình");
    }//GEN-LAST:event_btnCodeActionPerformed

    private void btnEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnglishActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Chào mừng bạn đến với tiếng anh");
    }//GEN-LAST:event_btnEnglishActionPerformed

    private void btnJapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJapanActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Chào mừng bạn đến với tiếng nhật bản");
    }//GEN-LAST:event_btnJapanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel DauHoi;
    private javax.swing.JLabel ThuTuCauHoi;
    private javax.swing.JLabel areax;
    private javax.swing.JButton btnCode;
    private javax.swing.JButton btnEnglish;
    private javax.swing.JButton btnJapan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel code;
    private javax.swing.JLabel description;
    private javax.swing.JLabel english;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel japanese;
    private javax.swing.JLabel line;
    private javax.swing.JLabel linex;
    private javax.swing.JLabel linexa;
    private javax.swing.JLabel linexb;
    private javax.swing.JLabel linexc;
    private javax.swing.JLabel liney;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
